

title: Data Analysis Services - daanse
email: bischofs@jena.de
description: >- # this means to ignore newlines until "baseurl:"
  This Site hold als Dokumentation and Tutorial for the daanse - Data Analysis Services Project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://daanse.org" # the base hostname & protocol for your site, e.g. http://example.com
github:
    username:  stbischof
theme: minima
plugins:
  - jekyll-feed
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item    
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
