name: eclipse dash ip-check

on:
  push:
    branches: [ main , snapshot ]
  pull_request:
    branches: [ main , snapshot ]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B org.eclipse.dash:license-tool-plugin:license-check -Dlicenses-check -Ddash.fail=true -Ddash.summary=DEPENDENCIES -DexcludeArtifactIds=$EXCLUDED_ARTIFACTS -P eclipse-licenses-check --file ./pom.xml
      env:
        EXCLUDED_ARTIFACTS: 'artid1,artid2'
